// Code generated by scripts/render_deployment_assets.py; DO NOT EDIT.
package deployment

const (
	DeploymentID        = "semester-2026-sandbox"
	HandbookRepository  = "IDEALLab/onboarding-IT"
	ExerciseRepository  = "soheylm-passport-sandbox/passport-exercises"
	ExerciseOwner       = "soheylm-passport-sandbox"
	ExerciseName        = "passport-exercises"
	ExtensionRepository = "soheylm-passport-sandbox/gh-passport"
	ExtensionRelease    = "v0.4.2"
	ControllerAppID     = "4827197"
	SupportAssignee     = "SoheylM"
)

const (
	ExerciseURL   = "https://github.com/" + ExerciseRepository
	HelpIssueURL  = ExerciseURL + "/issues/new?template=passport-help.yml"
	PullURLPrefix = ExerciseURL + "/pull/"
)
